version: '3.9'

services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: helpdesk-sql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SQL_SA_PASSWORD}
    ports:
      - "1433:1433"

  api:
    build:
      context: .
      dockerfile: HelpDesk.API/Dockerfile
    container_name: helpdesk-api
    depends_on:
      - sqlserver
    ports:
      - "5000:80"
    environment:
      - ConnectionStrings__Default=${DB_CONNECTION_STRING}

  notification-worker:
    build:
      context: .
      dockerfile: HelpDesk.NotificationWorker/Dockerfile
    container_name: helpdesk-notification
    depends_on:
      - api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ServiceBus__ConnectionString=${SERVICEBUS_CONNECTION_STRING}
      - ServiceBus__QueueName=ticket-create
      
  audit-worker:
    build:
      context: .
      dockerfile: HelpDesk.AuditWorker/Dockerfile
    container_name: helpdesk-audit
    depends_on:
      - api